# Generated by Django 4.2.4 on 2023-08-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0002_alter_order_customer_alter_order_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название камня')),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='gems',
        ),
        migrations.AlterField(
            model_name='client',
            name='spent_money',
            field=models.PositiveIntegerField(verbose_name='Спущенные деньги'),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(max_length=50, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.CharField(blank=True, max_length=50, verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.CharField(blank=True, max_length=50, verbose_name='Камень'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='client',
            name='gems',
            field=models.ManyToManyField(to='apitest.gem', verbose_name='Камни'),
        ),
    ]
